package application;

import java.io.File;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ColorPicker;
import javafx.scene.control.Label;
import javafx.scene.control.Slider;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

public class SceneRechercheSonController implements Initializable{
	

	 
	@FXML
	private Button buttonAdmin;
	

	
	 
	@FXML
	private Button buttonRetourner;
	@FXML
	private Button buttonRecherche;
	@FXML
	private TextField entrerRecherche;
	@FXML
	private Button buttonChoisirFichier;

	// Event Listener on Button[#buttonAdmin].onAction
	@FXML
	public void clickButtonAdmin(ActionEvent event) throws Exception {
    	Parent root = FXMLLoader.load(getClass().getResource("SceneMot_De_Passe.fxml"));
    	Scene scene = new Scene(root);
    	Stage stage = (Stage)((Node)event.getSource()).getScene().getWindow();
    	stage.setScene(scene);
    	stage.show();
	}
	// Event Listener on Button[#buttonRetourner].onAction
	@FXML
	public void clickButtonRetourner(ActionEvent event) throws Exception{
 	Parent root = FXMLLoader.load(getClass().getResource("MainScene.fxml"));
 	Scene scene = new Scene(root);
 	Stage stage = (Stage)((Node)event.getSource()).getScene().getWindow();
 	stage.setScene(scene);
 	stage.show();
	}
	// Event Listener on Button[#buttonRecherche].onAction
	@FXML
	public void clickButtonRecherche(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#entrerRecherche].onAction
	@FXML
	public void entrerRecherche(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#buttonChoisirFichier].onAction
	@FXML
	public void clickButtonChoisirFichier(ActionEvent event) {
		
		    // Créer une instance de FileChooser
		    FileChooser fileChooser = new FileChooser();

		    // Définir le titre de la fenêtre de sélection de fichiers
		    fileChooser.setTitle("Sélectionner un fichier");

		    // Récupérer la référence à la fenêtre principale
		    Stage stage = (Stage) buttonChoisirFichier.getScene().getWindow();

		    // Vérifier si la référence est valide avant d'ouvrir la boîte de dialogue
		    if (stage != null) {
		        File selectedFile = fileChooser.showOpenDialog(stage);

		        // Vérifier si un fichier a été sélectionné
		        if (selectedFile != null) {
		            // Extraire le nom du fichier à partir du chemin absolu
		            String fileName = selectedFile.getName();
		            // Mettre le nom du fichier sélectionné dans le TextField
		            entrerRecherche.setText(fileName);
		            
		            
		        }
		    }
		}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		entrerRecherche.setEditable(false);
	}

		
		
}